feature: new rule to check that region_id in station_information exists
MobilityData/gbfs-validator-java pull request #105
Opened 2024-12-18 12:40 UTC by hbruch

This PR adds a new rule, which checks that `station.region_id` in `station_information` feed is defined in the `system_regions` feed.

2024-12-18 13:34 UTC, testower requested changes
Just a minor naming error. Also, can we add this new rule to the README please :)

2024-12-18 13:34 UTC, testower commented on src/main/java/org/entur/gbfs/validation/validator/rules/NoInvalidReferenceToRegionInStationInformation.java
> +      JSONArray vehicleTypeIds = JsonPath
Probably a copy-paste error

```suggestion
      JSONArray regionIds = JsonPath
```

2024-12-18 13:34 UTC, testower commented on src/main/java/org/entur/gbfs/validation/validator/rules/NoInvalidReferenceToRegionInStationInformation.java
> +      regionIdSchema.put("enum", vehicleTypeIds);
```suggestion
      regionIdSchema.put("enum", regionIds);
```

2024-12-18 15:25 UTC, hbruch commented on src/main/java/org/entur/gbfs/validation/validator/rules/NoInvalidReferenceToRegionInStationInformation.java
> +      JSONArray vehicleTypeIds = JsonPath
Yes...

2024-12-27 08:58 UTC, testower approved these changes

2024-12-27 09:40 UTC, merged